import type { Metadata } from 'next';
import { StackProvider, StackTheme } from '@stackframe/stack';
import { stackClientApp } from '../stack/client';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Navigation } from '@/components/navigation';
import { Suspense } from 'react';
import { ThemeModeScript, ThemeProvider } from 'flowbite-react';
import { flowbiteTheme } from '@/flowbite-theme';
import { ProgressBar } from '@/components/progress-bar';
import { Skeleton } from '@/components/skeleton';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StackProvider app={stackClientApp}>
          <StackTheme>
            <Suspense fallback={null}>
              <ProgressBar>
                <ThemeProvider theme={flowbiteTheme}>
                  <Navigation />
                  {children}
                </ThemeProvider>
              </ProgressBar>
            </Suspense>
          </StackTheme>
        </StackProvider>
      </body>
    </html>
  );
}
